name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create .env files
      run: |
        echo "MONGODB_AUTH_URI=mongodb://localhost:27017/test_auth" >> auth/.env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> auth/.env

        echo "MONGODB_PRODUCT_URI=mongodb://localhost:27017/test_product" >> product/.env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> product/.env
        echo "LOGIN_TEST_USER=${{ secrets.LOGIN_TEST_USER }}" >> product/.env
        echo "LOGIN_TEST_PASSWORD=${{ secrets.LOGIN_TEST_PASSWORD }}" >> product/.env

    - name: Install dependencies
      run: |
        cd auth && npm ci
        cd ../product && npm ci
        cd ..

    # ✅ Start the auth service first
    - name: Start auth service
      run: |
        cd auth
        nohup npm start &>/dev/null &
        sleep 10 # đợi server khởi động hoàn toàn

    # ✅ Run tests for auth (server đã sẵn sàng)
    - name: Run auth tests
      run: |
        cd auth
        npm test

    # ✅ Tạo test user cho product tests
    - name: Create test user for product
      run: |
        curl -X POST http://localhost:3000/register \
          -H "Content-Type: application/json" \
          -d '{"username": "'${{ secrets.LOGIN_TEST_USER }}'", "password": "'${{ secrets.LOGIN_TEST_PASSWORD }}'"}' \
          || true

    # ✅ Chạy test cho product
    - name: Run product tests
      run: |
        cd product
        npm test
