name: CI 
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MONGODB_HOST: mongodb

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0

      - name: Create .env file
        run: |
          echo "MONGODB_AUTH_URI=mongodb://${MONGODB_HOST}:27017/test_auth" >> auth/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> auth/.env
          echo "MONGODB_PRODUCT_URI=mongodb://${MONGODB_HOST}:27017/test_product" >> product/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> product/.env
          echo "LOGIN_TEST_USER=${{ secrets.LOGIN_TEST_USER }}" >> product/.env
          echo "LOGIN_TEST_PASSWORD=${{ secrets.LOGIN_TEST_PASSWORD }}" >> product/.env

      - name: Install dependencies
        run: |
          cd auth && npm ci
          cd ../product && npm ci
          cd ..

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..10}; do
            if mongosh "mongodb://${MONGODB_HOST}:27017/test_auth" --eval "db.runCommand({ ping: 1 })"; then
              echo "MongoDB is ready!"
              break
            fi
            echo "Waiting for MongoDB..."
            sleep 5
          done

      - name: Run tests for auth
        run: |
          cd auth
          npm test -- --timeout 30000 --exit
